export const NAMING_SEQUENCE_KEYS = [
  "PURCHASE_ORDER",
  "GOODS_RECEIPT_NOTE",
  "PURCHASE_INVOICE",
  "STOCK_TRANSFER",
  "SALES_QUOTATION",
  "SALES_ORDER",
  "SALES_INVOICE",
  "CUSTOMER_PAYMENT",
  "SALES_CREDIT_NOTE",
  "GENERAL_LEDGER",
] as const;

export const VALUATION_METHOD_OPTIONS = ["FIFO", "MWAC"] as const;
